#!/usr/bin/env python

# Run this before you deploy it on replicate
import torch
from diffusers.utils import load_image
from diffusers import DiffusionPipeline, StableDiffusionControlNetPipeline, ControlNetModel
from diffusers import UniPCMultistepScheduler
from controlnet_aux import OpenposeDetector
import os
import sys
import urllib

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL,CONTROLNET,MODEL_ID, CONTROLNET_CACHE, MODEL_ID_CACHE, MODEL_CACHE

# Make cache folders
if not os.path.exists(CONTROLNET_CACHE):
    os.makedirs(CONTROLNET_CACHE)

if not os.path.exists(MODEL_ID_CACHE):
    os.makedirs(MODEL_ID_CACHE)

if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)


model = OpenposeDetector.from_pretrained(
    MODEL,
    cache_dir=MODEL_CACHE,
)

controlnet = ControlNetModel.from_pretrained(
    CONTROLNET,
    torch_dtype=torch.float16,
    cache_dir=CONTROLNET_CACHE,
)

controlnet.save_pretrained(CONTROLNET_CACHE)

pipe = DiffusionPipeline.from_pretrained(
     MODEL_ID,
     torch_dtype=torch.float16,
     cache_dir=MODEL_ID_CACHE,
    )
pipe.save_pretrained(MODEL_ID_CACHE, safe_serialization=True)
# if not os.path.exists(MODEL_ID_CACHE + "/realitycheckXL_alpha11.safetensors"):
#     print("Downloading model realitycheckXL_alpha11 ")
#     urllib.request.urlretrieve("https://stableai-space.fra1.digitaloceanspaces.com/models/sdxl_models/realitycheckXL_alpha11.safetensors", MODEL_ID_CACHE + "/realitycheckXL_alpha11.safetensors")


# append project directory to path so predict.py can be imported
# sys.path.append('.')
# from predict import MODEL_CACHE
MODEL_CACHE = "cache"

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

# Download GFPGANv1.4
os.system("cd cache && wget https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth")

# Download inswapper_128.onnx
os.system("cd cache && wget https://huggingface.co/ashleykleynhans/inswapper/resolve/main/inswapper_128.onnx")